[package]
name = "cex_stock"
version = "0.1.0"
authors = ["Paul Castle <paul.castle@gmail.com>"]
edition = "2018"

[dependencies]
scraper = "0.10.0"
select = "0.4.2"
reqwest = "0.9.17"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
error-chain = "0.12.1"
